#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 15 01:34:18 2023

@author: steven
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

mu, sigma = 0, 0.1
my_gauss = np.random.default_rng().normal(mu, sigma, size = 1000)
count, bins, ignored = plt.hist(my_gauss, 30, density = True)
plt.plot(bins, 1/(sigma*np.sqrt(2*np.pi))*np.exp(-(bins-mu)**2/(2*sigma**2)))

plt.plot(my_gauss_2)