#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 15 20:41:12 2023

@author: steven
"""

import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

os.system('clear')
%clear
%reset -f

# Loading Data
table_cells = pd.read_table("hw4_data.txt", delim_whitespace=True, skiprows=[1])
# Creating Header Array
table_header = np.genfromtxt('hw4_data.txt', dtype=str)
table_header = table_header[0:2]
table_header[0,0]= 'Date'
table_header[1,0]= 'dt'


# Rip Date and Times out of the table
year = table_cells.loc[:,'YY'].astype(str)
month = table_cells.loc[:,'MM'].astype(str)
day = table_cells.loc[:,'DD'].astype(str)
hour = table_cells.loc[:,'hh'].astype(str)
minute = table_cells.loc[:,'mm'].astype(str)

# Create datetime punctuation
dashes, colons, time = np.empty(year.size, dtype=str),np.empty(year.size, dtype=str),np.empty(year.size, dtype=str)
dashes[:],colons[:],time[:]='-',':','T'

# Produce an Array of date time
my_datetime = np.add(year,dashes)
my_datetime = np.add(my_datetime, month)
my_datetime = np.add(my_datetime, dashes)
my_datetime = np.add(my_datetime, day)
my_datetime = np.add(my_datetime, time)
my_datetime = np.add(my_datetime, hour)
my_datetime = np.add(my_datetime, colons)
my_datetime = np.add(my_datetime, minute)
my_datetime = pd.to_datetime(my_datetime)

# Replace Year column with datetime
table_cells['YY'] = my_datetime
# Remove Unnecessary columns
table_cells.drop(['MM','DD','hh','mm'],axis=1, inplace=True)
table_header = np.delete(table_header,(1,2,3,4),axis=1)

# Create Plot of Air Temperature against Datetime
fig1 = plt.figure()
plt.plot(table_cells['YY'],table_cells['ATMP'])
plt.gcf().autofmt_xdate()
plt.title('Air Temperature by Time')
plt.xlabel('Date')
plt.ylabel("Air Temperature (C)")
plt.show()

# Scatter Plot of Waveheight by wind speed
fig2 = plt.figure() 
plt.scatter(table_cells['WSPD'],table_cells['WVHT'])
plt.title('Wave Height by Wind Speed')
plt.xlabel('Wind Speed (m/s)')
plt.ylabel('Wave Height (m)')

# Resample Datetime to get average per day
export_table = table_cells.set_index('YY').resample('D').mean()
export_table = export_table.reset_index()
# Exporting Data as CSV
export_table = export_table.round(0).to_numpy()
export_table = np.concatenate((table_header,export_table))
export_table = pd.DataFrame(export_table)
export_table.to_csv('hw4_export.csv',index=True)



